# fly.toml app configuration file generated for staging-chitti-meet on 2023-08-09T13:19:10+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "staging-chitti-meet"
primary_region = "ams"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
